"""add_author_and_book_extra_fields

Revision ID: 1e0588ec5e84
Revises: 21a56dd2fcc9
Create Date: 2026-10-09 19:01:00.116463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e0588ec5e84'
down_revision: Union[str, Sequence[str], None] = '21a56dd2fcc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('authors', sa.Column('joined_date', sa.Date(), nullable=True))
    op.add_column('books', sa.Column('author_royalty_per_copy', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('books', sa.Column('last_royalty_payout_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'last_royalty_payout_date')
    op.drop_column('books', 'author_royalty_per_copy')
    op.drop_column('authors', 'joined_date')
    op.drop_column('authors', 'city')
    # ### end Alembic commands ###
